sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
  - cd LibraryCardAPI
  - echo "We are in the right folder"
script:
  - docker-compose build
before-deploy:
  - echo "$DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag librarycardapi:latest $DOCKER_USERNAME/librarycardapi:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/librarycardapi:$TRAVIS_JOB_ID;
  on:
    branch: main
notifactions:
  email: false